/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ElementMetadata, } from "./components/stencil-component/elementMetadata";
import { CommandStore, } from "./components/stencil-component/commandStore";
export namespace Components {
    interface StencilComponent {
        "collapsed": boolean;
        "metadata": string | object;
        "result": () => Promise<ElementMetadata>;
        "setCommandStore": (value: CommandStore) => Promise<void>;
    }
}
declare global {
    interface HTMLStencilComponentElement extends Components.StencilComponent, HTMLStencilElement {
    }
    var HTMLStencilComponentElement: {
        prototype: HTMLStencilComponentElement;
        new (): HTMLStencilComponentElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-component": HTMLStencilComponentElement;
    }
}
declare namespace LocalJSX {
    interface StencilComponent {
        "collapsed"?: boolean;
        "metadata"?: string | object;
        "onData-update"?: (event: CustomEvent<object>) => void;
    }
    interface IntrinsicElements {
        "stencil-component": StencilComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-component": LocalJSX.StencilComponent & JSXBase.HTMLAttributes<HTMLStencilComponentElement>;
        }
    }
}
