/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CommandStore, } from "./components/stencil-component/commandStore";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilComponent {
        "collapsed": boolean;
        "metadata": string;
        "setCommandStore": (value: CommandStore) => Promise<void>;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilComponentElement extends Components.StencilComponent, HTMLStencilElement {
    }
    var HTMLStencilComponentElement: {
        prototype: HTMLStencilComponentElement;
        new (): HTMLStencilComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stencil-component": HTMLStencilComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilComponent {
        "collapsed"?: boolean;
        "metadata"?: string;
        "onData-update"?: (event: CustomEvent<object>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stencil-component": StencilComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-component": LocalJSX.StencilComponent & JSXBase.HTMLAttributes<HTMLStencilComponentElement>;
        }
    }
}
